import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {freshState,sanitizeState,discover,answer,purchase,missionDone,buildGraph,nearestGraphPoint,findRoute,distance,pointInPolygon,clipPolyline,largestConnectedGraph} from '../dist/core.js';
import {PLACES,SHOP,MISSIONS,REGIONS} from '../dist/content.js';

test('first discovery pays the stated reward exactly once',()=>{const s=freshState();assert.deepEqual(discover(s,'library'),{coins:50,xp:80});assert.equal(discover(s,'library'),null);assert.equal(s.coins,50);assert.equal(s.discovered.length,1);});
test('wrong quiz answers and premature answers never pay or penalize',()=>{const s=freshState();assert.equal(answer(s,'library',0).invalid,true);discover(s,'library');const before={coins:s.coins,xp:s.xp};assert.equal(answer(s,'library',2).correct,false);assert.deepEqual({coins:s.coins,xp:s.xp},before);assert.equal(s.solved.length,0);});
test('correct quiz rewards are idempotent and survive reloading',()=>{const s=freshState();discover(s,'library');assert.deepEqual(answer(s,'library',0),{correct:true,coins:20,xp:30});const restored=sanitizeState(JSON.parse(JSON.stringify(s)));assert.deepEqual(answer(restored,'library',0),{correct:true,coins:0,xp:0});assert.equal(restored.coins,70);assert.equal(restored.xp,110);});
test('shop deducts once then toggles the actual equipped item',()=>{const s=freshState();for(const id of ['library','office','park'])discover(s,id);assert.equal(s.coins,150);assert.deepEqual(purchase(s,'gold-cape'),{ok:true,bought:true});assert.equal(s.coins,30);assert.equal(s.equipped.outfit,'gold');purchase(s,'gold-cape');assert.equal(s.coins,30);assert.equal(s.equipped.outfit,'default');purchase(s,'gold-cape');assert.equal(s.equipped.outfit,'gold');assert.equal(s.owned.length,1);});
test('insufficient coins never buy an item or become negative',()=>{const s=freshState();assert.deepEqual(purchase(s,'gold-cape'),{ok:false,reason:'balance'});assert.equal(s.coins,0);assert.deepEqual(s.owned,[]);});
test('saved input is bounded, known and finite',()=>{const s=sanitizeState({version:1,coins:Infinity,xp:-900,discovered:['library','library','unknown'],solved:['council','library'],owned:['unknown'],equipped:{outfit:'hack'},note:'a'.repeat(2000),position:[NaN,3],speed:999});assert.deepEqual(s.discovered,['library']);assert.deepEqual(s.solved,['library']);assert.equal(s.coins,70);assert.equal(s.note.length,1000);assert.equal(s.position,null);assert.equal(s.equipped.outfit,'default');assert.equal(s.speed,1);});
test('full journey covers both counties, intangible culture and enough cosmetic funds',()=>{const s=freshState();for(const p of PLACES){discover(s,p.id);answer(s,p.id,p.quiz.answer);}assert.equal(missionDone(s,MISSIONS.at(-1)),true);assert(PLACES.some(p=>p.county==='예산군'));assert(PLACES.some(p=>p.type==='intangible'));for(const item of SHOP)assert.equal(purchase(s,item.id).ok,true);assert(s.coins>=0);const restored=sanitizeState(s);assert.equal(restored.coins,s.coins);assert.equal(restored.xp,s.xp);});


import {districtAt,inGeometry,canVisit,placeRadius,updateEncounters,SpatialIndex} from '../dist/geography.js';
import {symbolKey,SYMBOLS} from '../dist/place-icons.js';
import {World} from '../dist/world.js';
import {Cartography,tileLayout} from '../dist/cartography.js';
import {CULTURE_PLACES} from '../dist/culture.js';
import {FACILITIES} from '../dist/facilities.js';
const data=JSON.parse(readFileSync(new URL('../dist/map-county.json',import.meta.url))),ml=111320*Math.cos(data.origin[1]*Math.PI/180),project=p=>[(p[0]-data.origin[0])*ml,(data.origin[1]-p[1])*111320],max=[(data.bounds[2]-data.bounds[0])*ml,(data.bounds[3]-data.bounds[1])*111320];
const mapped=PLACES.filter(p=>!p.remote).map(p=>({...p,point:project([p.lon,p.lat])}));

test('one map contains all eleven Hongseong districts and every mapped destination',()=>{assert.equal(REGIONS.length,1);assert.equal(REGIONS[0].id,'county');const ds=data.districts.filter(d=>d.county==='홍성군');assert.equal(ds.length,11);assert.equal(ds.filter(d=>d.name.endsWith('읍')).length,3);for(const d of ds)assert.equal(districtAt(d.center,data.districts).name,d.name);for(const p of mapped){assert.equal(p.region,'county');assert(p.point.every((v,i)=>v>=0&&v<=max[i]),p.name);}});
test('live address resolves Naepo, Hongseong, Gwangcheon, coast, Yesan and every office',()=>{for(const [geo,name]of [[[126.67118,36.65611],'홍북읍'],[[126.6608,36.60129],'홍성읍'],[[126.625,36.5046],'광천읍'],[[126.47125,36.53865],'서부면'],[[126.679,36.665],'삽교읍']])assert.equal(districtAt(geo,data.districts)?.name,name);for(const p of FACILITIES.filter(p=>p.name.includes('행정복지센터')))assert.equal(districtAt([p.lon,p.lat],data.districts)?.county+' '+districtAt([p.lon,p.lat],data.districts)?.name,p.area);});
test('all directions can open every place and distant clicks cannot claim discovery',()=>{for(const p of mapped){const radius=placeRadius(p);for(const [x,y]of [[1,0],[-1,0],[0,1],[0,-1]]){assert(canVisit([p.point[0]+x*(radius-1),p.point[1]+y*(radius-1)],p));assert(!canVisit([p.point[0]+x*(radius+25),p.point[1]+y*(radius+25)],p));}}});
test('automatic entry opens once, rearms on exit, works for revisits and fast crossings',()=>{const p={id:'p',point:[0,0],type:'daily'},held=new Set();assert.equal(updateEncounters([p],[-100,0],[-20,0],held).length,1);assert.equal(updateEncounters([p],[-20,0],[20,0],held).length,0);updateEncounters([p],[20,0],[100,0],held);assert.equal(updateEncounters([p],[100,0],[-110,0],held).length,1);assert.equal(updateEncounters([p],[-110,0],[-110,0],held).length,0);});
test('airplane preserves direct travel to every destination even with the roads toggle',()=>{for(const p of mapped){const w={state:{movementMode:"roads",travelSpeed:"plane"},events:{},position:project(data.start),max,clamp:World.prototype.clamp};assert(World.prototype.walkTo.call(w,p.point,p.id));assert.deepEqual(w.route,[p.point]);assert.equal(w.routePlace,p.id);assert.equal(distance(w.position,w.route[0]),distance(w.position,p.point));}const w={state:{movementMode:"roads",travelSpeed:"plane"},events:{},position:[300,300],max,clamp:World.prototype.clamp};World.prototype.walkTo.call(w,[300,-500]);assert.deepEqual(w.route,[[300,1]]);});
test('real coastline preserves ocean, dry harbor and island holes',()=>{const f=data.features.find(f=>f.tags.water==='sea'),geometry={type:'Polygon',coordinates:[f.points,...f.holes]};assert(inGeometry([126.445,36.545],geometry));assert(!inGeometry([126.47125,36.53865],geometry));assert(!inGeometry(data.start,geometry));assert(f.holes.length>0);});
test('old v1 and v2 saves migrate to county longitude and latitude with the same rewards',()=>{const s=freshState();discover(s,'library');answer(s,'library',0);delete s.region;delete s.locations;s.position=[740,990];const a=sanitizeState(s);assert.equal(a.coins,70);assert.equal(a.region,'county');assert(Math.abs(a.locations.county[0]-(126.663+740/(111320*Math.cos(36.665*Math.PI/180))))<1e-10);for(const region of ['naepo','yongbong','namdang']){const b=sanitizeState({...s,region,locations:{[region]:[126.471,36.539]}});assert.deepEqual(b.locations.county,[126.471,36.539]);assert.equal(b.coins,70);}assert.deepEqual(sanitizeState({...s,region:'county',locations:{county:[126.66,36.6]}}).locations.county,[126.66,36.6]);});
test('required facility types have distinct persistent icons and commercial names are masked',()=>{const keys=['government','post','bank','elementary','middle','high','university','mart'];for(const k of keys)assert(FACILITIES.some(p=>p.symbol===k),k);assert.equal(new Set(keys.map(k=>SYMBOLS[k].path)).size,8);assert.equal(FACILITIES.filter(p=>p.name.includes('행정복지센터')).length,11);assert(FACILITIES.some(p=>p.name==='롯0마트 홍성점'));assert(FACILITIES.some(p=>p.name.startsWith('하0로마트')));for(const p of FACILITIES.filter(p=>['bank','mart'].includes(p.symbol)))assert(p.name.includes('0'),p.name);for(const p of mapped)assert(SYMBOLS[symbolKey(p)]);});
test('schools use current verified names and moved campuses; old names do not appear',()=>{for(const p of FACILITIES.filter(p=>['elementary','middle','high'].includes(p.symbol))){assert(p.schoolSource?.address,p.name);assert.equal(p.originalName,p.schoolSource.name);}assert.equal(FACILITIES.filter(p=>p.name==='홍북초등학교').length,1);assert.equal(FACILITIES.find(p=>p.name==='홍북초등학교').lon,126.685208);assert.equal(FACILITIES.find(p=>p.name==='홍주초등학교').area,'홍성군 홍북읍');for(const n of ['덕명초등학교','광동초등학교','구 광천중학교'])assert(!FACILITIES.some(p=>p.name===n));});
test('spatial rendering retrieves crossing features without searching the whole county',()=>{const a={bounds:[0,0,30,30]},b={bounds:[1000,1000,2000,2000]},c={bounds:[0,10,1500,10]},idx=new SpatialIndex([a,b,c]);assert.deepEqual(new Set(idx.query([5,5,20,20])),new Set([a,c]));assert.deepEqual(idx.query([200,200,300,300]),[]);});
test('all imagery, modules, source links and place identifiers are present',()=>{assert.equal(new Set(PLACES.map(p=>p.id)).size,PLACES.length);for(const p of PLACES){assert(p.source.startsWith('https://')||existsSync(new URL('../dist/'+p.source,import.meta.url)));assert(p.quiz.answer>=0&&p.quiz.answer<3);}for(const f of [...PLACES.map(p=>p.image),data.terrain,'assets/map-view-county.webp','assets/facility-location-sources.json','county-boundaries.json','geography.js','place-icons.js','cartography.js',...['green','gold'].flatMap(s=>['back','front'].map(d=>'assets/chibi-'+s+'-'+d+'.webp'))])assert(existsSync(new URL('../dist/'+f,import.meta.url)),f);});


test('shrinking and enlarging the map rebuilds crisp tiles with gap-free coverage',()=>{
 const oldDocument=globalThis.document;let created=0;
 const context=()=>({setTransform(){},fillRect(){},drawImage(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},fill(){},stroke(){},setLineDash(){},save(){},restore(){},translate(){},rotate(){},strokeText(){},fillText(){}});
 globalThis.document={createElement:()=>{created++;return{width:0,height:0,getContext:()=>context()};}};
 try{
  const w={features:[],data:{districts:[],terrainLabels:[]},max:[40000,30000],width:1200,height:800,dpr:2,zoom:1.75,camera:[16000,15000],screen:World.prototype.screen,fromScreen:World.prototype.fromScreen};
  const c=Object.create(Cartography.prototype);Object.assign(c,{w,index:new SpatialIndex([]),tiles:new Map(),terrain:{naturalWidth:0},image:{naturalWidth:0}});
  for(const zoom of [1.75,.6,.1,.6,1.75,3.6,.1,3.6]){
   w.zoom=zoom;const boxes=[];c.draw({save(){},restore(){},drawImage(tile,x,y,width,height){assert.equal(tile.width,516);assert.equal(tile.height,516);assert(Number.isFinite(width));assert(tile.width/width>=w.dpr);boxes.push([x,y,x+width,y+height]);}});
   // All corners and interior samples are covered after zooming both directions.
   for(let x=0;x<=w.width;x+=100)for(let y=0;y<=w.height;y+=100)assert(boxes.some(b=>x>=b[0]&&x<=b[2]&&y>=b[1]&&y<=b[3]),`unpainted ${zoom}: ${x},${y}`);
   assert(c.tiles.size<=c.cacheLimit);assert(c.cacheLimit<=Math.max(64,c.visibleKeys.size+16));assert([...c.tiles.keys()].some(k=>k.startsWith(tileLayout(zoom,w.dpr).resolution+':')));
  }
  assert(created>1);
 }finally{globalThis.document=oldDocument;}
});
test('culture categories are distinct, all addresses match polygons, and events are contextual',()=>{
 const keys=['heritage','birthplace','memorial','temple','historicSchool','oldoffice','museum','gallery','festival','market','specialty','food','cafe','park','forest','garden','viewpoint'];
 assert.equal(new Set(keys.map(k=>SYMBOLS[k].path)).size,keys.length);
 for(const p of mapped){const d=districtAt([p.lon,p.lat],data.districts);assert.equal(d.county+' '+d.name,p.area,p.name);}
 for(const p of CULTURE_PLACES){assert(p.locationSource?.startsWith('https://'));if(p.symbol==='festival')assert(p.locationNote&&p.pages.some(s=>s.includes('매일 행사가 열리는 것은 아니야')));if(p.symbol==='cafe')assert(p.name.includes('0'));if(['food','specialty'].includes(p.symbol))assert(p.pages.some(s=>s.includes('특정 가게 한 곳을 뜻하지는 않아')));}
 assert(CULTURE_PLACES.some(p=>p.name==='결성농요농사박물관'));assert(CULTURE_PLACES.some(p=>p.originalName==='스타벅스 충남도청점'));assert.equal(CULTURE_PLACES.find(p=>p.name==='한국고건축박물관').county,'예산군');
});
test('top speed selection is preserved without changing old rewards',()=>{for(const travelSpeed of ['walk','fast','faster']){const s=freshState();discover(s,'library');s.travelSpeed=travelSpeed;const restored=sanitizeState(s);assert.equal(restored.travelSpeed,travelSpeed);assert.equal(restored.coins,50);}assert.equal(sanitizeState({...freshState(),travelSpeed:'invalid'}).travelSpeed,'walk');});
